/**
 * Created by bigben on 2017/12/12.
 */

/*commom*/

export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const LOGOUT_PRINCIPAL = 'LOGOUT_PRINCIPAL';
export const SET_UPLOAD_POLICY = 'SET_UPLOAD_POLICY'
export const SET_UPLOAD_FILE = 'SET_UPLOAD_FILE'
export const SET_DICT_DATA = 'SET_DICT_DATA'
export const SET_USER_TASK_LIST = 'SET_USER_TASK_LIST'
export const SET_FUND_COMPANY_LIST = 'SET_FUND_COMPANY_LIST'
export const SET_USER_TASK_COUNT = 'SET_USER_TASK_COUNT'

export const RESET_STATES = 'RESET_STATES'


/*companymanagement*/
export const GET_COMPANY_BUILD_LIST = 'GET_COMPANY_BUILD_LIST'
export const GET_COMPANY_FETCH_NAME_LIST = 'GET_COMPANY_FETCH_NAME_LIST'
export const ADD_NEW_COMPANY = 'ADD_NEW_COMPANY'
export const ADD_NEW_COMPANY_CONTACT = 'ADD_NEW_COMPANY_CONTACT'
export const SET_COMPANY_CONTACT_LIST = 'SET_COMPANY_CONTACT_LIST'
export const SET_COMPANY_BASIC = 'SET_COMPANY_BASIC'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const DELETE_COMPANY_CONTACT = 'DELETE_COMPANY_CONTACT'
export const SET_COMPANY_SUBMIT_RESULT = 'SET_COMPANY_SUBMIT_RESULT'
export const GET_COMPANY_SEARCH_RESULT = 'GET_COMPANY_SEARCH_RESULT'


/*project*/
export const SET_PROJECT_FLOWING_LIST = 'SET_PROJECT_FLOWING_LIST'
export const SET_PROJECT_FLOWED_LIST = 'SET_PROJECT_FLOWED_LIST'
export const SET_PROJECT_CUSTOMER_LIST = 'SET_PROJECT_CUSTOMER_LIST'
export const SET_ADD_BUYER_RANDOM = 'SET_ADD_BUYER_RANDOM'
export const SET_ANALYZE_INVOICE_LIST = 'SET_ANALYZE_INVOICE_LIST'

export const SET_PROJECT_DETAIL = 'SET_PROJECT_DETAIL'
export const SET_PROJECT_BUYER_LIST = 'SET_PROJECT_BUYER_LIST'
export const SET_PROJECT_SELLER_LIST = 'SET_PROJECT_SELLER_LIST'
export const SET_PROJECT_USER_LIST = 'SET_PROJECT_USER_LIST'

export const SET_PROJECT_QUOTA_DETAIL = 'SET_PROJECT_QUOTA_DETAIL'
export const SET_PROJECT_FINANCING_DETAIL = 'SET_PROJECT_FINANCING_DETAIL'
export const SET_PROJECT_AGREEMENT_DETAIL = 'SET_PROJECT_AGREEMENT_DETAIL'
export const SET_PROJECT_MEMO_LIST = 'SET_PROJECT_MEMO_LIST'

export const SET_SCHEME_PRICE_DETAIL = 'SET_SCHEME_PRICE_DETAIL'

export const SET_REFUSE_REASON_LIST = 'SET_REFUSE_REASON_LIST'
export const SET_PROJECT_PROGRESS_IMG = 'SET_PROJECT_PROGRESS_IMG'

export const SET_PROJECT_ANALYSE_CHART_LIST = 'SET_PROJECT_ANALYSE_CHART_LIST'
export const SET_PROJECT_ANALYSE_PROPORTION_LIST = 'SET_PROJECT_ANALYSE_PROPORTION_LIST'

/*contract*/
export const SET_SIGNED_LIST = 'SET_SIGNED_LIST'
export const SET_UNSIGNED_LIST = 'SET_UNSIGNED_LIST'
export const SET_PROTOCOL_LIST = 'SET_PROTOCOL_LIST'
export const SET_SIGNED_INFO = 'SET_SIGNED_INFO'
export const SET_SIGNED_DIGRAM = 'SET_SIGNED_DIGRAM'



/*company*/
export const SET_COMPANY_CONTACT_DETAIL = 'SET_COMPANY_CONTACT_DETAIL'
export const SET_COMPANY_TRADE_DETAIL = 'SET_COMPANY_TRADE_DETAIL'


/*capitalmanagement*/
export const SET_CAPITAL_LIST = 'SET_CAPITAL_LIST'
export const SET_CAPITAL_LIST_CHANGE = 'SET_CAPITAL_LIST_CHANGE'
export const SET_CAPITAL_BASIC_INFO = 'SET_CAPITAL_BASIC_INFO'
export const SET_CAPITAL_BASIC_CONTACT = 'SET_CAPITAL_BASIC_CONTACT'
export const SET_CAPITAL_BASIC_COOPERATION = 'SET_CAPITAL_BASIC_COOPERATION'
export const SET_CAPITAL_BASIC_SCHEME = 'SET_CAPITAL_BASIC_SCHEME'
export const SET_CAPITAL_SUBMIT_RESULT = 'SET_CAPITAL_SUBMIT_RESULT'
export const SET_CAPITAL_COOPERATION_PERSON = 'SET_CAPITAL_COOPERATION_PERSON'
export const SET_CAPITAL_PROGRESS_IMG = 'SET_CAPITAL_PROGRESS_IMG'
export const SET_CAPITAL_ALL_LIST = 'SET_CAPITAL_ALL_LIST'
export const SET_CAPITAL_WAIT_DISTRIBUTE_LIST = 'SET_CAPITAL_WAIT_DISTRIBUTE_LIST'
export const SET_CAPITAL_WAIT_GIVEOUT_LIST = 'SET_CAPITAL_WAIT_GIVEOUT_LIST'
export const SET_CAPITAL_WAIT_SETTLE_LIST = 'SET_CAPITAL_WAIT_SETTLE_LIST'
export const SET_CAPITAL_WAIT_AUDIT_LIST = 'SET_CAPITAL_WAIT_AUDIT_LIST'
export const SET_CAPITAL_DETAIL = 'SET_CAPITAL_DETAIL'
export const SET_CAPITAL_DISTRIBUTE_PROGRESS_IMG = 'SET_CAPITAL_DISTRIBUTE_PROGRESS_IMG'



/*settlementmanagement*/
export const SET_SETTLE_COLLECTION_LIST = 'SET_SETTLE_COLLECTION_LIST'
export const SET_SETTLE_COLLECTION_UPLOAD_RESULT = 'SET_SETTLE_COLLECTION_UPLOAD_RESULT'
export const SET_SETTLE_COLLECTION_SUBMIT_RESULT = 'SET_SETTLE_COLLECTION_SUBMIT_RESULT'

/*trade*/
export const SET_TRADE_LIST = 'SET_TRADE_LIST'
export const SET_SELLER_OPTIONS = 'SET_SELLER_OPTIONS'
export const SET_BUYER_OPTIONS = 'SET_BUYER_OPTIONS'
export const SET_FINANCING_APP_LIST = 'SET_FINANCING_APP_LIST'
export const SET_FINANCING_APP_INFO = 'SET_FINANCING_APP_INFO'
export const SET_TRADE_DIGRAM = 'SET_TRADE_DIGRAM'
export const SET_TRADE_APPLY_INFO = 'SET_TRADE_APPLY_INFO'
export const SET_TRADE_APPLY_INVOICE_LIST = 'SET_TRADE_APPLY_INVOICE_LIST'
export const SET_TRADE_APPLY_PROVIDER_LIST = 'SET_TRADE_APPLY_PROVIDER_LIST'
export const SET_TRADE_INVOICE_LIST = 'SET_TRADE_INVOICE_LIST'
export const SET_TRADE_ITEM_LIST = 'SET_TRADE_ITEM_LIST'
export const SET_UNVERIFIED_ORDER = 'SET_UNVERIFIED_ORDER'
export const SET_ASSETS_LIST = 'SET_ASSETS_LIST'
export const SET_ASSETS_INFO = 'SET_ASSETS_INFO'


export const SET_VERIFY_ORDER_INFO = 'SET_VERIFY_ORDER_INFO'
export const SET_TRADE_PROGRESS_IMG = 'SET_TRADE_PROGRESS_IMG'
export const SET_TRADE_FINANCING_INVOICE_LIST = 'SET_TRADE_FINANCING_INVOICE_LIST'



/*enterprise*/
export const SET_COMPANY_DATA_LIST = 'SET_COMPANY_DATA_LIST'
export const SET_ENTERPRISE_LIMIT_DETAIL = 'SET_ENTERPRISE_LIMIT_DETAIL'
export const SET_ENTERPRISE_LIMIT_LIST = 'SET_ENTERPRISE_LIMIT_LIST'
export const SET_CUSTOMER_USE_LIST = 'SET_CUSTOMER_USE_LIST'
export const SET_ENTERPRISE_ASSIGN_LIST = 'SET_ENTERPRISE_ASSIGN_LIST'

/*system*/
export const SET_SYSTEM_DICTIONARY_TYPE_LIST = 'SET_SYSTEM_DICTIONARY_TYPE_LIST'
export const SET_SYSTEM_DICTIONARY_ITEM_LIST = 'SET_SYSTEM_DICTIONARY_ITEM_LIST'
export const SET_SYSTEM_DICTIONARY_ITEM_ACTION_RESULT = 'SET_SYSTEM_DICTIONARY_ITEM_ACTION_RESULT'














